# Create NumPy Array from Python list

In [2]:
#Inicialize a Python List
python_list = [2, 4, 6, 8, 10]

In [3]:
#Display the list
python_list

[2, 4, 6, 8, 10]

In [1]:
#Import numpy library
import numpy as np

In [4]:
#Converting the python_list to numpy array
numpy_array1 = np.array(python_list)

In [6]:
#Display the numpy array
numpy_array1

array([ 2,  4,  6,  8, 10])

# Compare Python List & NumPy Array

In [7]:
# Create two python list say 'list_x' and 'list_y'
list_x = list(range(100000))
list_y = list(range(100000))

In [8]:
# Create two numpy array (say 'arr_x' and 'arr_y') using above two list
arr_x = np.array(list_x)
arr_y = np.array(list_y)

In [9]:
# Define a function to calculate sum using pythom lists (list_x, list_y)
def list_sum():
    z = [] # a empty list to store sum
    for i in range(len(list_x)):
        z.append(list_x[i] + list_y[i])

In [10]:
# Define a function to calculate sum using numpy array (arr_x, arr_y)
def numpy_arr_sum():
    # In numpy we can directñy perform sum element-wise as
    z = arr_x + arr_y

In [11]:
# Import Timer class from timeit library
from timeit import Timer

In [14]:
timer_obj1 = Timer("list_sum()", "from __main__ import list_sum")
timer_obj2 = Timer("numpy_arr_sum()", "from __main__ import numpy_arr_sum")

print("Pure python version:", timer_obj1.timeit(1000))
print("Numpy version:", timer_obj2.timeit(1000))

Pure python version: 16.263225924999915
Numpy version: 0.07289384700015944


# Shape, Size and Data Type of an Array
#### Create a NumPy Array

In [15]:
# creating a NumPy array using python nested list
arr = np.array([[5,6,7],[9,9,10],[11,12,13],[1,2,3]])
arr

array([[ 5,  6,  7],
       [ 9,  9, 10],
       [11, 12, 13],
       [ 1,  2,  3]])

#### Size of an Array

In [16]:
# Checking the size of a NumPy Array
arr.size

12

#### Data Type of Array

In [17]:
# Checking Data Type of a NumPy Array
arr.dtype

dtype('int64')

#### Shape of an Array

In [18]:
arr

array([[ 5,  6,  7],
       [ 9,  9, 10],
       [11, 12, 13],
       [ 1,  2,  3]])

In [19]:
arr.shape

(4, 3)

#### Dimension of an Array

In [20]:
arr

array([[ 5,  6,  7],
       [ 9,  9, 10],
       [11, 12, 13],
       [ 1,  2,  3]])

In [21]:
# Checking the dimension of a NumPy Array
arr.ndim

2

#### type() function and dtype method
Everything in Python is an object.

Suppose you have an object and want to know what type of object it is; you will use the type() function to get this information.

Now you know the object is a NumPy ndarray. To know the data type in that array, you will use the attribute ‘.dtype’. This is also called the type of NumPy array.

In [22]:
type(arr)

numpy.ndarray

In [23]:
arr.dtype

dtype('int64')

Note that Python lists don’t support the ‘.dtype’ attribute or any other methods supported by a NumPy array.

# Creating Basic NumPy Arrays
### array()

In [24]:
# Using array()
arr = np.array([[1,2,5,7],[5,2,7,6],[6,2,0,8]])
arr

array([[1, 2, 5, 7],
       [5, 2, 7, 6],
       [6, 2, 0, 8]])

### arange()

In [26]:
#Using arange()
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### zeros()

In [27]:
#Using zeros()
arr3 = np.zeros(5)
arr3

array([0., 0., 0., 0., 0.])

### ones()

In [28]:
#Using ones()
arr4 = np.ones(4)
arr4

array([1., 1., 1., 1.])

### linspace()

In [30]:
#Using linspace()
arr5 = np.linspace(start=5,stop=10,num=5)
arr5

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

# Basic methods on Array and Reshaping
### Add, Remove ans Sort
##### Adding Element

In [33]:
# Say we have the following array
arr6 = np.array([2,5,7,3,4,6])
arr6

array([2, 5, 7, 3, 4, 6])

In [35]:
# adding an elemnte in the array
np.append(arr6,15) # 15 will be added at the end of the array

array([ 2,  5,  7,  3,  4,  6, 15])

In [36]:
# We can also use python list to append an element
l = [2,5,4,6,7]
arr7 = np.append(l,10)
arr7

array([ 2,  5,  4,  6,  7, 10])

In [37]:
type(arr7)

numpy.ndarray

In [38]:
np.append(arr7,[11,12,17])

array([ 2,  5,  4,  6,  7, 10, 11, 12, 17])

## Caution!!
A NumPy array doesn’t support the append() method directly on the array. The given snippet will clear this:



In [40]:
# NOte: NumPy array doesn't suppert append directly on the array
arr7.append(20)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [41]:
 # but a Python list suports the append() method directly on the Python list
 l = [5,10,15] # A Python list
 l.append(20) # adding an element in Python list
 l

[5, 10, 15, 20]

### Removing an Element

In [43]:
# Create a NumPy Array
arr8 = np.array([2,5,7,3,4,6])
arr8

array([2, 5, 7, 3, 4, 6])

In [44]:
# Remove an element at particular index
np.delete(arr8,1) # element at index 1 will be remove from the array

array([2, 7, 3, 4, 6])

### Sorting an Array

In [45]:
arr8

array([2, 5, 7, 3, 4, 6])

In [46]:
np.sort(arr8)

array([2, 3, 4, 5, 6, 7])

### Reshaping a Python List

In [47]:
# you can also reshape a Python list
# But the resultant object will be a numpy array

# Create a Python list
l = [0,1,2,3,4,5,6,7,8,9,10,11]

#Reshape l in shape (2,6)
reshaped_arr = np.reshape(l,(2,6))
reshaped_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [48]:
type(reshaped_arr)

numpy.ndarray

In [50]:
arr9 = np.arange(20)
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [51]:
# Using reshape() directly on arr
arr9.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Positive Indexing
### Rows and Columns Indexes in an Array

The index in Python start in 0

### Positive Single Indexing in an Array

In [52]:
arr10 = np.array([10,20,30,40])
arr10

array([10, 20, 30, 40])

In [54]:
arr10[2]

30

### Positive Single Indexing in Python Nested List

In [55]:
# Create a Python list
python_list2 = [[2,4,6],[8,10,12]]

# Getting an element fron Python list
# Say you want to get the element 4 which is present in first sublist
python_list2[0][1]

4

### Positive Single Indexing in a NumPy Array

In [56]:
# Crete NumPy array using Python list
num_arr = np.array(python_list2)
num_arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [57]:
num_arr[0]

array([2, 4, 6])

In [58]:
num_arr[0,0]

2

### Positive Index Intervals in a NumPy Array

In [59]:
num_arr[0,0:2]

array([2, 4])

In [64]:
arr

array([[1, 2, 5, 7],
       [5, 2, 7, 6],
       [6, 2, 0, 8]])

In [65]:
arr[0:3,1:3]

array([[2, 5],
       [2, 7],
       [2, 0]])